services:
  - type: webapp
    name: greencart-frontend
    env: static
    buildCommand: npm run build
    publishDirectory: dist
    routes:
      - type: rewrite
        source: /(.*)
        destination: /index.html
